# Generated by Django 6.0.3 on 2026-03-12 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0002_driver_team'),
    ]

    operations = [
        migrations.RenameField(
            model_name='driver',
            old_name='championships',
            new_name='constructor_championships',
        ),
        migrations.AddField(
            model_name='driver',
            name='drivers_championships',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
