# Generated by Django 6.0.3 on 2026-03-12 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0003_rename_championships_driver_constructor_championships_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='driver',
            old_name='constructor_championships',
            new_name='championships',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='drivers_championships',
        ),
    ]
