# Generated by Django 6.0.3 on 2026-03-12 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('circuit', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('race_date', models.DateField()),
                ('season', models.PositiveIntegerField()),
            ],
        ),
    ]
