# Generated by Django 6.0.3 on 2026-03-12 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0004_rename_constructor_championships_driver_championships_and_more'),
        ('races', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RaceResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('points', models.PositiveIntegerField()),
                ('fastest_lap', models.BooleanField(default=False)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drivers.driver')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='races.race')),
            ],
        ),
        migrations.AddField(
            model_name='race',
            name='drivers',
            field=models.ManyToManyField(through='races.RaceResult', to='drivers.driver'),
        ),
    ]
