# Generated by Django 6.0.3 on 2026-03-12 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('founded', models.PositiveIntegerField()),
                ('team_principal', models.CharField(max_length=100)),
                ('championships', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
